version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Run Tests
          command: |
            npm t
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
            - bin/*
            - package.json
            - package-lock.json
            - README.md

  publish-npm-beta:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM
          command: |
            printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
            npm whoami
      - run:
          name: Deploy to NPM
          command: |
            npm publish --access public --tag beta

  publish-npm:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM
          command: |
            printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
            npm whoami
      - run:
          name: Deploy to NPM
          command: |
            npm publish --access public

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish-npm-beta:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/
          context: danielemery-npm
      - publish-npm:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
          context: danielemery-npm
