version: 2.1
jobs:
  publish-npm-beta:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM
          command: |
            printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
            npm whoami
      - run:
          name: Deploy to NPM
          command: |
            npm publish --access public --tag beta

  publish-docker-beta:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=demery/docker-react
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run NPM install
          command: |
            npm ci --production
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG --build-arg DOCKER_REACT_VERSION=$TAG .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG

  publish-npm:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM
          command: |
            printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
            npm whoami
      - run:
          name: Deploy to NPM
          command: |
            npm publish --access public

  publish-docker:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=demery/docker-react
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run NPM install
          command: |
            npm ci --production
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG --build-arg DOCKER_REACT_VERSION=$TAG .
            docker tag $REGISTRY:$TAG $REGISTRY:latest
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG
            docker push $REGISTRY:latest

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish-npm-beta:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/
          context: danielemery-npm
      - publish-npm:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
          context: danielemery-npm
      - publish-docker-beta:
          requires:
            - test
            - publish-npm-beta
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/
          context: demery-dockerhub-deploy
      - publish-docker:
          requires:
            - test
            - publish-npm
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
          context: demery-dockerhub-deploy
